name: simpel_habit_tracker_byfar
description: "A simple habit tracker app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0' # Pastikan sesuai dengan SDK yang digunakan

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
