name: simpel_habit_tracker_byfar
description: "A simple habit tracker app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0' # Pastikan SDK sesuai dengan versi yang digunakan

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Gunakan versi yang lebih stabil
  build_runner: ^2.4.7 # Pastikan kompatibel dengan SDK yang digunakan
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
